### PR TITLE
Test input checking functions

### PR DESCRIPTION
**Pull request by jdblischak**
Follow up to #136. I had forgotten to test the input checking functions.

Changes include:

* Renamed `input_check_scale()` to `input_check_scalar()` since it requires a single value
* Fixed a bug in `get_analysis_date()` (both `cond1` and `cond2` checked `min_n_overall`)

My assumptions (please correct me if I'm wrong):

* `input_check_scalar()` requires non-negative numbers (ie accepts zero)
* `input_check_vector()` requires positive numbers (ie rejects zero)
* `min_n_overall` and `sum(min_n_per_stratum)` can equal the sample size (the code and the error message disagreed, and I went with the code)

Open questions:

* Do the input checking functions require whole numbers? Currently they accept floating point numbers
* Should `input_check_vector()` accept a vector of multiple missing values? (`input_check_vector(NA, NA)`)

### CODE REVIEW

**Review by LittleBeannie — APPROVED** [review]
Thanks for correcting my bad wording!

**Comment by jdblischak** [comment]
Yujie answered my questions on Teams. My summary below:

> * Do the input checking functions require whole numbers? Currently they accept floating point numbers

The following arguments require whole numbers: target_event_overall, min_n_overall, target_event_per_stratum, min_n_per_stratum

> * Should `input_check_vector()` accept a vector of multiple missing values? (`input_check_vector(NA, NA)`)

Yes. Directly from Yujie:

> For example, min_n_per_stratum = c(NA, NA, NA) is equivalent to min_n_per_stratum = NA

**Comment by jdblischak** [comment]
Ready to go as long as CI passes

**Review by nanxstats — COMMENTED** [review]
I wonder if we should use the is whole number implementation directly from `?base::is.integer` code examples.

```r
is_whole_number <- function(x) trunc(x) == x
is.wholenumber <- function(x, tol = .Machine$double.eps^0.5) abs(x - round(x)) < tol

is_whole_number(3.000000000000001)
# [1] FALSE
is_whole_number(3.0000000000000001)
# [1] TRUE

is.wholenumber(3.0000001)
# [1] FALSE
is.wholenumber(3.00000001)
# [1] TRUE
```

The main difference is the tolerance: `.Machine$double.eps` (inexplicitly 1e-16) vs. `.Machine$double.eps^0.5` (explictly 1e-8).

If we are dealing with data that's likely to have minute computational inaccuracies from arithmetic operations, the `is.wholenumber()` method looks safer. Also, it was used in [`gsDesign::toInteger()`](https://github.com/keaven/gsDesign/blob/6de6583d621bf2fd0bff8e4b4f4b755d77ee407d/R/toInteger.R#L159).

**Review by nanxstats — APPROVED** [review]
Thanks for the update - looks great

**Pull request merged**
