### PR TITLE
add sample size and events to `sim_gs_n` per analysis per simulation

### LINKED ISSUE #207: More output of `sim_gs_n`
It would be good for `sim_gs_n` to return sample size (n) and events (event) for each record returned.

### PR DESCRIPTION
**Pull request by LittleBeannie**
Closes #207

### CODE REVIEW

**Review by nanxstats — CHANGES_REQUESTED** [review]
Instead of removing `n` and `event` from `observed`, I think the better way to update the tests is to add these to `expected`.

**Comment by LittleBeannie** [comment]
> Instead of removing `n` and `event` from `observed`, I think the better way to update the tests is to add these to `expected`.

Agreed! I'm uncertain about the origin of the "magic number" in the expected . I will reach out to John and inquire about the feasibility of including `n` (sample size) and `event` (number of events) in the expected object of `test-unvalidated-sim_gs_n.R`.

Hi @jdblischak, could you please let us know if it is possible to incorporate `n` and `event` in the expected object of the `test-unvalidated-sim_gs_n.R`?

**Comment by jdblischak** [comment]
> if it is possible to incorporate `n` and `event` in the expected object of the `test-unvalidated-sim_gs_n.R`?

@LittleBeannie Yes, I obtained `expected` by running `constructive::construct(observed)`

> I'm uncertain about the origin of the "magic number" in the expected .

These are backwards compatibility tests. There is nothing magic about them. I cannot refactor the code without having tests to ensure I don't break anything.

**Comment by LittleBeannie** [comment]
> > if it is possible to incorporate `n` and `event` in the expected object of the `test-unvalidated-sim_gs_n.R`?
> 
> @LittleBeannie Yes, I obtained `expected` by running `constructive::construct(observed)`
> 
> > I'm uncertain about the origin of the "magic number" in the expected .
> 
> These are backwards compatibility tests. There is nothing magic about them. I cannot refactor the code without having tests to ensure I don't break anything.

Thank you for your quick response! I encountered an issue while attempting to run `constructive::construct(observed)` directly in the console. It seems that I might have missed the correct way to run the code. Could you please help update the `expected`?

**Review by jdblischak — APPROVED** [review]

**Review by nanxstats — APPROVED** [review]
Very nice, thanks for the update ✨

**Pull request merged**
