### PR TITLE
296 fix cran pre tests

### PR DESCRIPTION
**Pull request by LittleBeannie**
To fix issue #296

### CODE REVIEW

**Comment by LittleBeannie** [comment]
Hi @jdblischak and @nanxstats, it looks like I only changed the DESCRIPTION file but the CMD check on macos is failed.  Do you happen to have any thoughts?

**Comment by jdblischak** [comment]
We fixed this error in the dev version of {gsDesign2}: https://github.com/Merck/simtrial/pull/262#issuecomment-2237609774

**Review by jdblischak — CHANGES_REQUESTED** [review]
I recommend releasing {gsDesign2} to CRAN (https://github.com/Merck/gsDesign2/pull/480), and then updating the `Imports` of {simtrial} to require this latest version with `>=`

**Comment by LittleBeannie** [comment]
Thanks for the suggestion! I will prepare the release of gsDesign2 first.

**Pull request closed without merging**
