### PR TITLE
Requestion gsDesign2 >= v1.1.3

### PR DESCRIPTION
**Pull request by LittleBeannie**
This PR follows #297. 

John might be off today. @nanxstats and @yihui, could you please review and approve it? I will prepare a CRAN submission after your approval.

### CODE REVIEW

**Review by yihui — APPROVED** [review]
I think that's good.

**Comment by yihui** [comment]
Oh actually you *might* not be able to pass the automated check on CRAN because **gsDesign2** 1.1.3 is too new, which may not be available on CRAN's check machines yet, but you can certainly try. If it fails to pass today, you can retry the submission tomorrow and I guess it should be able to pass automatically. Feel free to ping me here if you encounter any problems during the submission.

**Review by nanxstats — APPROVED** [review]
Yihui has a valid point but you'll know during CRAN submission. Also, the dependencies in `DESCRIPTION` are sorted alphabetically but that's only a minor style thing.

**Comment by LittleBeannie** [comment]
Thank you, @yihui, for the suggestions!

**Pull request merged**
