### PR TITLE
change `fixedBlockRand` to `randomize_by_fixed_block`

### PR DESCRIPTION
**Pull request by LittleBeannie**

### CODE REVIEW

**Review by nanxstats — CHANGES_REQUESTED** [review]
Instead of `rand_by_fixed_block`, let's use `randomize_by_fixed_block`.

**Comment by LittleBeannie** [comment]
> randomize_by_fixed_block

Good suggestion! @lili-ling-msd, let's change the function name to `randomize_by_fixed_block`.

**Comment by LittleBeannie** [comment]
Hi @nanxstats, could you please approve this PR? Since I initially created this PR as a demo for Lili and Xintong, I am not allowed to approve it now. Thanks!

**Review by nanxstats — APPROVED** [review]
Thanks for the patch - approved.

**Pull request merged**
